export const serverLocation = 'http://localhost:4000/'
export const messageSendPath = 'messageReceive/'
export const messageGetPath = 'messageListRequest/'
export const chatsListGetPath = 'chatsListRequest/'
export const submitUserNameAndPasswordPath = 'login/'
export const submitNewUserPath = 'newUser/'